// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiODImVzi4c-PeAL1m24eWezmo0rEf6yI',
    appId: '1:943405544329:web:c0f72626b97fc07f012758',
    messagingSenderId: '943405544329',
    projectId: 'hmszuvy',
    authDomain: 'hmszuvy.firebaseapp.com',
    storageBucket: 'hmszuvy.firebasestorage.app',
    measurementId: 'G-8G9KGEWQYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93MMlcvFRnVPjRdQc4Pu9wVSYyucIthc',
    appId: '1:943405544329:android:d344693ca2945273012758',
    messagingSenderId: '943405544329',
    projectId: 'hmszuvy',
    storageBucket: 'hmszuvy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZwJ07yysMZGkDN06RsI1eTtDRJXbwwM',
    appId: '1:943405544329:ios:dcc55fb71590fe5f012758',
    messagingSenderId: '943405544329',
    projectId: 'hmszuvy',
    storageBucket: 'hmszuvy.firebasestorage.app',
    iosBundleId: 'com.example.100msDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZwJ07yysMZGkDN06RsI1eTtDRJXbwwM',
    appId: '1:943405544329:ios:dcc55fb71590fe5f012758',
    messagingSenderId: '943405544329',
    projectId: 'hmszuvy',
    storageBucket: 'hmszuvy.firebasestorage.app',
    iosBundleId: 'com.example.100msDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiODImVzi4c-PeAL1m24eWezmo0rEf6yI',
    appId: '1:943405544329:web:b502f2c0aca5fc46012758',
    messagingSenderId: '943405544329',
    projectId: 'hmszuvy',
    authDomain: 'hmszuvy.firebaseapp.com',
    storageBucket: 'hmszuvy.firebasestorage.app',
    measurementId: 'G-SR77Y3K4C7',
  );
}
